metis: update to snapshot with build fix for strerror_r() usage
/home/balay/soft/mpich-4.0.1/bin/mpicc -Dmetis_EXPORTS -I/home/balay/petsc/arch-linux-c-debug/externalpackages/git.metis/GKlib -I/home/balay/petsc/arch-linux-c-debug/externalpackages/git.metis/include -I/home/balay/petsc/arch-linux-c-debug/externalpackages/git.metis/libmetis/. -I/home/balay/petsc/arch-linux-c-debug/externalpackages/git.metis/petsc-build/include -fPIC -Wno-lto-type-mismatch -Wno-stringop-overflow -g -O0 -DLINUX -D_FILE_OFFSET_BITS=64 -std=c99 -fno-strict-aliasing -fPIC -Wall -pedantic -Wno-unused-variable -Wno-unknown-pragmas -DDEBUG -DNDEBUG -DNDEBUG2 -DUSE_GKRAND -DHAVE_EXECINFO_H -DHAVE_GETLINE -g -fPIC -Wno-lto-type-mismatch -Wno-stringop-overflow -g -O0 -fPIC -MD -MT libmetis/CMakeFiles/metis.dir/__/GKlib/error.c.o -MF CMakeFiles/metis.dir/__/GKlib/error.c.o.d -o CMakeFiles/metis.dir/__/GKlib/error.c.o -c /home/balay/petsc/arch-linux-c-debug/externalpackages/git.metis/GKlib/error.c
/home/balay/petsc/arch-linux-c-debug/externalpackages/git.metis/GKlib/error.c: In function ‘gk_strerror’:
/home/balay/petsc/arch-linux-c-debug/externalpackages/git.metis/GKlib/error.c:183:3: error: implicit declaration of function ‘strerror_r’; did you mean ‘strerror’? [-Wimplicit-function-declaration]
  183 |   strerror_r(errnum, buf, 1024);
      |   ^~~~~~~~~~