hwloc: disable for pgf90 build (as -lnuma from PGI conflicts with system version)
/usr/lib/x86_64-linux-gnu/libhwloc.so: undefined reference to `set_mempolicy@libnuma_1.1'