tests: move ex151 out of complex tests to avoid compile errors on windows
  const struct {PetscInt i,j; PetscScalar v;} entries[] = {{0,3,1.},{1,2,2.},{2,1,3.},{2,5,4.},{3,0,5.},{3,6,6.},{4,1,7.},{4,4,8.}};

/home/sbalay/petsc.clone-2/bin/win32fe/win32fe cl -o ex151.o -c -DMPICH_SKIP_MPICXX -MT -GR -EHsc -Z7 -Zm200  -TP    -I/home/sbalay/petsc.clone-2/include
-I/home/sbalay/petsc.clone-2/arch-mswin-cxx-cmplx/include -I/cygdrive/c/Program\ Files/MPICH2/include    `pwd`/ex151.c
ex151.c
C:\cygwin\home\sbalay\PETSC~2.CLO\src\mat\examples\tests\ex151.c(18) : error C2440: 'initializing' : cannot convert from 'const int' to 'const struct '
        No constructor could take the source type, or constructor overload resolution was ambiguous
C:\cygwin\home\sbalay\PETSC~2.CLO\src\mat\examples\tests\ex151.c(18) : error C2440: 'initializing' : cannot convert from 'const int' to 'const struct '
        No constructor could take the source type, or constructor overload resolution was ambiguous
C:\cygwin\home\sbalay\PETSC~2.CLO\src\mat\examples\tests\ex151.c(18) : error C2440: 'initializing' : cannot convert from 'const double' to 'const struct '
        No constructor could take the source type, or constructor overload resolution was ambiguous