msys2: fix link error with incorrect library order - when /c/PROGRA~2/MICROS~2/MPI/Lib/x64/msmpi.lib is used
wrong:
gcc -g3  -g3  -I/home/balay/petsc/include -I/home/balay/petsc/arch-msys-c-debug/include -I/c/PROGRA~2/MICROS~2/MPI/Include     -Wl,-rpath,/home/balay/petsc/arch-msys-c-debug/lib -L/home/balay/petsc/arch-msys-c-debug/lib /c/PROGRA~2/MICROS~2/MPI/Lib/x64/msmpi.lib ex2.c  -lpetsctao -lpetscts -lpetscsnes -lpetscksp -lpetscdm -lpetscmat -lpetscvec -lpetscsys -llapack -lblas -lgdi32 -luser32 -ladvapi32 -lkernel32 -lquadmath -o ex2
C:/msys64/home/balay/petsc/arch-msys-c-debug/lib/libpetscksp.a(itcl.o): In function `PetscMPIParallelComm':
C:/msys64/home/balay/petsc/include/petsclog.h:428: undefined reference to `MPI_Comm_size'

fixed:
gcc -g3  -g3  -I/home/balay/petsc/include -I/home/balay/petsc/arch-msys-c-debug/include -I/c/PROGRA~2/MICROS~2/MPI/Include     -Wl,-rpath,/home/balay/petsc/arch-msys-c-debug/lib -L/home/balay/petsc/arch-msys-c-debug/lib ex2.c  -lpetsctao -lpetscts -lpetscsnes -lpetscksp -lpetscdm -lpetscmat -lpetscvec -lpetscsys /c/PROGRA~2/MICROS~2/MPI/Lib/x64/msmpi.lib -llapack -lblas -lgdi32 -luser32 -ladvapi32 -lkernel32 -lquadmath -o ex2

Reported-by: Pierre Jolivet <pierre.jolivet@enseeiht.fr>