win: fix build errors [wrt complex, from cxx sources] in a clanguage=c build
        CXX arch-mswin-cl-nof/obj/src/sys/objects/device/impls/host/hostcontext.o
hostcontext.cxx
D:\balay\petsc.x\include\petsc/private/petscimpl.h(482): error C2065: 'PetscComplex': undeclared identifier
D:\balay\petsc.x\include\petsc/private/petscimpl.h(482): error C2059: syntax error: '>'
D:\balay\petsc.x\include\petsc/private/petscimpl.h(482): error C2332: 'struct': missing tag name
D:\balay\petsc.x\include\petsc/private/petscimpl.h(482): error C3306: 'Petsc::util::<unnamed-tag>': unnamed class template is not allowed
D:\balay\petsc.x\include\petsc/private/petscimpl.h(482): error C2913: explicit specialization; 'Petsc::util::<unnamed-tag>' is not a specialization of a class template
D:\balay\petsc.x\include\petsc/private/petscimpl.h(482): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\balay\petsc.x\include\petsc/private/petscimpl.h(482): error C2146: syntax error: missing '>' before identifier 'PetscComplex'
D:\balay\petsc.x\include\petsc/private/petscimpl.h(482): error C2913: explicit specialization; 'Petsc::util::<unnamed-tag>' is not a specialization of a class template
make[3]: *** [gmakefile:203: arch-mswin-cl-nof/obj/src/sys/objects/device/impls/host/hostcontext.o] Error 2