fix(section): Use PetscReal for non-standard FP
Compile errors when using `--with-scalar-type=complex --with-precision=__float128` due to illegal cast:
```
petsc/src/vec/is/section/interface/section.c:2630:65: error: invalid cast from type 'PetscScalar' {aka '__complex__ _Float128'} to type 'double'
 2630 |     PetscCall(PetscViewerASCIISynchronizedPrintf(viewer, " %g", (double)((PetscScalar *)array)[index]));
      |                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Also changed the function name to be more reflection of what it does.

Reported-by: Jose E. Roman <jroman@dsic.upv.es>