install: fix RDict.db error duing 'make install'
Patch-from: Matthew Knepley <knepley@gmail.com>
Reported-by: Torquil Macdonald Sørensen <torquil@gmail.com>
Reported-by: "Klinvex, Alicia Marie" <amklinv@sandia.gov>

*** Using PETSC_DIR=/home/amklinv/PETScDir/petsc PETSC_ARCH=arch-linux2-cxx-debug ***
No cached configure in RDict at arch-linux2-cxx-debug/lib/petsc/conf/RDict.db
Traceback (most recent call last):
  File "./config/install.py", line 380, in <module>
    Installer(sys.argv[1:]).run()
  File "./config/install.py", line 373, in run
    self.runsetup()
  File "./config/install.py", line 334, in runsetup
    self.setup()
  File "./config/install.py", line 60, in setup
    self.setupModules()
  File "./config/install.py", line 51, in setupModules
    self.setCompilers  = self.framework.require('config.setCompilers',         None)
AttributeError: 'NoneType' object has no attribute 'require'
make: *** [install] Error 1