remove code that assumes MPI_2INT is a macro.
This is a continuation of the fix in bcb1dc63284765edb2c98905bc313bc2d01136a1

/p/work1/bctacct/sw/app/math/PETSc/3.11.2/include/petscmath.h:708:19: error: ‘MPI_2INT’ redeclared as different kind of symbol
 #define MPIU_2INT MPI_2INT
                   ^
/p/work1/bctacct/sw/app/math/PETSc/3.11.2/src/sys/objects/init.c:76:14: note: in expansion of macro ‘MPIU_2INT’
 MPI_Datatype MPIU_2INT = 0;
              ^
In file included from /p/work1/bctacct/sw/app/math/PETSc/3.11.2/include/petscsys.h:134:0,
                 from /p/work1/bctacct/sw/app/math/PETSc/3.11.2/src/sys/objects/init.c:9:
/p/app/sgi/mpt/mpt-2.15/include/mpi.h:143:2: note: previous definition of ‘MPI_2INT’ was here
  MPI_2INT  = 34,
  ^