Fix regression from !7824
In file included from src/petsc4py/PETSc.c:1224:
In file included from src/lib-petsc/compat.h:16:
src/lib-petsc/compat/plexexodusii.h:11:16: error: conflicting types for 'DMPlexCreateExodus'
   11 | PetscErrorCode DMPlexCreateExodus(PETSC_UNUSED MPI_Comm comm, PETSC_UNUSED PetscInt n , PETSC_UNUSED PetscBool flg, PETSC_UNUSED DM *dm){PetscPlexExodusIIError;}
      |                ^
include/petscdmplex.h:204:29: note: previous declaration is here
  204 | PETSC_EXTERN PetscErrorCode DMPlexCreateExodus(MPI_Comm, PetscExodusIIInt, PetscBool, DM *);
      |                             ^