Fix compilation error for nvcc in optimized code with AVX-512 (march=native on my GPU workstation)
for some reason, the host compiler fails with this error message
/home/zampins/Devel/petsc/include/../src/mat/impls/aij/seq/aij.h(535): error: identifier "_mm512_reduce_add_pd" is undefined

This optimized C kernel is not used in the GPU classes, so it is safe to skip its declaration