Insure that struct is at least as long as the size we need it to align to For example with complex __float128 PetscScalar it needs to be at least 32 bytes long otherwise one gets the error
/home/travis/build/dalcinl/petsc/include/petsc/private/dmnetworkimpl.h:43:3:
 error: alignment of array elements is greater than element size

Time: .1 hour
Reported-by: Lisandro Dalcin <dalcinl@gmail.com>