CI: workaround cython-3.0.1 breakage [where -Werror is used]
src/petsc4py/PETSc.c:42033:11: error: incompatible pointer to integer conversion assigning to 'MPI_Comm' (aka 'int') from 'void *' [-Wint-conversion]
  __pyx_r = NULL;
          ^ ~~~~
etc..