pastix: update to snapshot with build fixes for MPI-3 errors [wrt OpenMPI-5.0]
/home/balay/petsc/arch-linux-c-debug/bin/mpicc   -fPIC -Wno-lto-type-mismatch -Wno-stringop-overflow -g -O0 -Wno-implicit-function-declaration -Wno-implicit-int -Wno-deprecated-non-prototype -fno-common -I/home/balay/petsc/arch-linux-c-debug/include  -DFORCE_INT32  -DWITH_HWLOC -I/home/balay/petsc/arch-linux-c-debug/include -DNUMA_ALLOC -DDISTRIBUTED -DWITH_SCOTCH -I/home/balay/petsc/arch-linux-c-debug/include  -DVERSION='""' -DX_ARCHi686_pc_linux -DDOF_CONSTANT  -DVERSION='""' -DX_ARCHi686_pc_linux -DDOF_CONSTANT -I./common/src -I./order/src -I./symbol/src -I./fax/src -I./perf/src -I./blend/src -I./kass/src -I./sopalin/src -I./utils/src -I./matrix_drivers/src -I./wrapper/src -I./sparse-matrix/src -Imurge/include  -DCHOL_SOPALIN -c sopalin/src/sopalin3d.c -o sopalin/obj/i686_pc_linux/sopalin3d.o
In file included from sopalin/src/sopalin3d.c:85:
sopalin/src/./sopalin_sendrecv.c: In function ‘po_send_one_fanin’:
/home/balay/petsc/arch-linux-c-debug/include/mpi.h:350:59: error: static assertion failed: "MPI_Address was removed in MPI-3.0.  Use MPI_Get_address instead."
  350 | #define THIS_FUNCTION_WAS_REMOVED_IN_MPI30(func, newfunc) _Static_assert(0, #func " was removed in MPI-3.0.  Use " #newfunc " instead.")
      |                                                           ^~~~~~~~~~~~~~
/home/balay/petsc/arch-linux-c-debug/include/mpi.h:3179:27: note: in expansion of macro ‘THIS_FUNCTION_WAS_REMOVED_IN_MPI30’
 3179 | #define MPI_Address(...)  THIS_FUNCTION_WAS_REMOVED_IN_MPI30(MPI_Address, MPI_Get_address)
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sopalin/src/./sopalin_sendrecv.c:1303:12: note: in expansion of macro ‘MPI_Address’
 1303 |   CALL_MPI MPI_Address(FANIN_INFOTAB(t),&(thread_data->gtaboffs[packnbr]));
      |            ^~~~~~~~~~~