64bit-indices: wierd error with system mpi & superlu_dist+ metis. Switch to download-openmpi [thrash:/sandbox/petsc/petsc.clone-3] petsc> mpicc -o conftest conftest.c -L/sandbox/petsc/petsc.clone-3/arch-linux-pkgs-64idx/lib -lsuperlu_dist_3.3 \ -llapack -lblas [thrash:/sandbox/petsc/petsc.clone-3] petsc> mpicc -o conftest conftest.c -L/sandbox/petsc/petsc.clone-3/arch-linux-pkgs-64idx/lib -lsuperlu_dist_3.3 \ -llapack -lblas -lparmetis /usr/lib/libmpich.so: undefined reference to `MPL_trfree' /usr/lib/libmpich.so: undefined reference to `MPL_env2str' /usr/lib/libmpich.so: undefined reference to `MPL_trlevel' /usr/lib/libmpich.so: undefined reference to `MPL_trvalid' /usr/lib/libmpich.so: undefined reference to `MPL_trmalloc' /usr/lib/libmpich.so: undefined reference to `MPL_trspace' /usr/lib/libmpich.so: undefined reference to `MPL_env2range' /usr/lib/libmpich.so: undefined reference to `MPL_trcalloc' /usr/lib/libmpich.so: undefined reference to `MPL_env2int' /usr/lib/libmpich.so: undefined reference to `MPL_trdump' /usr/lib/libmpich.so: undefined reference to `MPL_putenv' /usr/lib/libmpich.so: undefined reference to `MPL_env2bool' /usr/lib/libmpich.so: undefined reference to `MPL_trstrdup' /usr/lib/libmpich.so: undefined reference to `MPL_trrealloc' /usr/lib/libmpich.so: undefined reference to `MPL_TrSetMaxMem' /usr/lib/libmpich.so: undefined reference to `MPL_trinit' /usr/lib/libmpich.so: undefined reference to `MPL_trDebugLevel' /usr/lib/libmpich.so: undefined reference to `MPL_trid' collect2: ld returned 1 exit status