Cannot use petscsnes inside definition of snessetapplicationcontext interface since it already includes such an interface
ex73f90t.o ex73f90t.F90
ex73f90t.F90:67.12:

        use petscsnes
            1
Error: 'snessetapplicationcontext' of module 'petscsnes', imported at (1), is also the name of the current program unit
ex73f90t.F90:78.12: