fix build on theta/cray triggered by 08eac2b88dd7869f1e41f7fa0824d878bc3956da
cc -dynamic   -fPIC -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -fstack-protector -Qunused-arguments -fvisibility=hidden -g3 -O0  -fPIC -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -fstack-protector -Qunused-arguments -fvisibility=hidden -g3 -O0    -I/lus/theta-fs0/projects/ci/ecp/working/thetalogin3/shell-01/cscstms/builds/aZ9WMnrn/001/anl-public/petsc/petsc/include -I/lus/theta-fs0/projects/ci/ecp/working/thetalogin3/shell-01/cscstms/builds/aZ9WMnrn/001/anl-public/petsc/petsc/arch-alcfci-theta-cray-opt/include -I/opt/cray/pe/netcdf-hdf5parallel/4.7.3.3/CRAYCLANG/9.0/include -I/opt/cray/pe/parallel-netcdf/1.12.0.1/CRAYCLANG/9.0/include     ex19.c  -Wl,-rpath,/lus/theta-fs0/projects/ci/ecp/working/thetalogin3/shell-01/cscstms/builds/aZ9WMnrn/001/anl-public/petsc/petsc/arch-alcfci-theta-cray-opt/lib -L/lus/theta-fs0/projects/ci/ecp/working/thetalogin3/shell-01/cscstms/builds/aZ9WMnrn/001/anl-public/petsc/petsc/arch-alcfci-theta-cray-opt/lib -Wl,-rpath,/opt/cray/pe/netcdf-hdf5parallel/4.7.3.3/CRAYCLANG/9.0/lib -L/opt/cray/pe/netcdf-hdf5parallel/4.7.3.3/CRAYCLANG/9.0/lib -Wl,-rpath,/opt/cray/pe/parallel-netcdf/1.12.0.1/CRAYCLANG/9.0/lib -L/opt/cray/pe/parallel-netcdf/1.12.0.1/CRAYCLANG/9.0/lib -Wl,-rpath,/lus/theta-fs0/projects/ci/ecp/working/thetalogin3/shell-01/cscstms/builds/aZ9WMnrn/001/anl-public/petsc/petsc/arch-alcfci-theta-cray-opt/lib -L/lus/theta-fs0/projects/ci/ecp/working/thetalogin3/shell-01/cscstms/builds/aZ9WMnrn/001/anl-public/petsc/petsc/arch-alcfci-theta-cray-opt/lib -lpetsc -lnetcdf -lpnetcdf -lchaco -lparmetis -lmetis -lz -lX11 -lquadmath -ldl -lstdc++ -o ex19
ld.lld: error: /lus/theta-fs0/projects/ci/ecp/working/thetalogin3/shell-01/cscstms/builds/aZ9WMnrn/001/anl-public/petsc/petsc/arch-alcfci-theta-cray-opt/lib/libpetsc.so: undefined reference to mpi_

Since the symbol 'mpi_' is coming from 'use mpi' - configure should also test with 'use mpi'