windows: fix FLINKER failure with 'gcc -fstack-protector' that gives
/home/petsc/petsc.next-4/arch-mswin-gnu/lib/libpetsc.a(init.o): In function `PetscOpenHistoryFile':
/home/petsc/petsc.next-4/src/sys/objects/init.c:142: undefined reference to `__stack_chk_fail'

Note: The issue is 'gcc - -fstack-protector' requires '-lssp_nonshared -lssp' - so fix the test code
to trigger this detection [when gfortran is used without this option]