CI: switch stage-1 to use gcc-12
And Use -O instead of -O3, this fixes:

         CC arch-linux-c-opt/obj/sys/memory/mtr.o
In file included from /scratch/svcpetsc/glci-builds/t7AQTxpb/2/petsc/petsc/include/petscsys.h:1184,
                 from /scratch/svcpetsc/glci-builds/t7AQTxpb/2/petsc/petsc/include/petsc/private/petscimpl.h:7,
                 from /scratch/svcpetsc/glci-builds/t7AQTxpb/2/petsc/petsc/src/sys/memory/mtr.c:5:
/scratch/svcpetsc/glci-builds/t7AQTxpb/2/petsc/petsc/src/sys/memory/mtr.c: In function 'PetscMallocView':
/scratch/svcpetsc/glci-builds/t7AQTxpb/2/petsc/petsc/src/sys/memory/mtr.c:916:13: error: 'PetscSortStrWithPermutation' accessing 4 bytes in a region of size 0 [-Werror=stringop-overflow=]
  916 |   PetscCall(PetscSortStrWithPermutation(n, (const char **)shortfunction, perm));
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/scratch/svcpetsc/glci-builds/t7AQTxpb/2/petsc/petsc/include/petscerror.h:435:17: note: in definition of macro 'PetscCall'
  435 |       ierr_q_ = __VA_ARGS__; \
      |                 ^~~~~~~~~~~
/scratch/svcpetsc/glci-builds/t7AQTxpb/2/petsc/petsc/src/sys/memory/mtr.c:916:13: note: referencing argument 3 of type 'PetscInt[0]' {aka 'int[]'}
  916 |   PetscCall(PetscSortStrWithPermutation(n, (const char **)shortfunction, perm));
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/scratch/svcpetsc/glci-builds/t7AQTxpb/2/petsc/petsc/include/petscerror.h:435:17: note: in definition of macro 'PetscCall'
  435 |       ierr_q_ = __VA_ARGS__; \
      |                 ^~~~~~~~~~~
/scratch/svcpetsc/glci-builds/t7AQTxpb/2/petsc/petsc/include/petscsys.h:2340:29: note: in a call to function 'PetscSortStrWithPermutation'
 2340 | PETSC_EXTERN PetscErrorCode PetscSortStrWithPermutation(PetscInt, const char *[], PetscInt[]);
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~