cmake: cmake-3.7.0 build fails on fedora28 - when libcrypto.so is installed - so update to latest version -3.11.1
This versionbuilds fine on opensolaris - so remove cmake-3.0.1 usage

In file included from /home/balay/tmp/petsc/arch-linux2-c-debug/externalpackages/cmake-3.7.0/Utilities/cmlibarchive/libarchive/archive_cryptor.c:32:
/home/balay/tmp/petsc/arch-linux2-c-debug/externalpackages/cmake-3.7.0/Utilities/cmlibarchive/libarchive/archive_cryptor_private.h:107:17: error: field ‘ctx’ has incomplete type
  EVP_CIPHER_CTX ctx;
                 ^~~