fix c++ build error
mpicxx -pthread -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -fstack-protector -g -fPIC -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -DPETSC_DIR=/home/balay/petsc -I/home/balay/petsc/arch-linux2-cxx-debug/include -I/home/balay/petsc/include -Isrc/include -I/usr/lib64/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c src/PETSc.c -o build/temp.linux-x86_64-2.7/arch-linux2-cxx-debug/src/PETSc.o
In file included from src/PETSc.c:4:
src/petsc4py.PETSc.c: In function ‘PyObject* __pyx_pf_8petsc4py_5PETSc_4SNES_66getFunction(PyPetscSNESObject*)’:
src/petsc4py.PETSc.c:183739:103: error: invalid conversion from ‘void*’ to ‘PetscErrorCode (**)(SNES, Vec, Vec, void*)’ {aka ‘int (**)(_p_SNES*, _p_Vec*, _p_Vec*, void*)’} [-fpermissive]
   __pyx_t_2 = __pyx_f_8petsc4py_5PETSc_CHKERR(SNESGetFunction(__pyx_v_self->snes, (&__pyx_v_f->vec), ((void *)(&__pyx_v_fun)), (&__pyx_v_ctx))); if (unlikely(__pyx_t_2 == ((int)-1))) __PYX_ERR(38, 277, __pyx_L1_error)
                                                                                                      ~^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/balay/petsc/include/petscts.h:7,
                 from /home/balay/petsc/include/petsc.h:29,
                 from src/petsc4py.PETSc.c:568,
                 from src/PETSc.c:4:
/home/balay/petsc/include/petscsnes.h:364:55: note:   initializing argument 3 of ‘PetscErrorCode SNESGetFunction(SNES, _p_Vec**, PetscErrorCode (**)(SNES, Vec, Vec, void*), void**)’
 PETSC_EXTERN PetscErrorCode SNESGetFunction(SNES,Vec*,PetscErrorCode (**)(SNES,Vec,Vec,void*),void**);
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~