Fix for use of macros with arguments when macro was used without arguments
E:\FGH\Git\Windows\petsc-3.17.1\src\mat\impls\aij\seq\aijmkl\aijmkl.c(148): warning C4003: not enough arguments for function-like macro invocation 'mkl_sparse_x_create_csr'
E:\FGH\Git\Windows\petsc-3.17.1\src\mat\impls\aij\seq\aijmkl\aijmkl.c(148): error C2059: syntax error: ','
E:\FGH\Git\Windows\petsc-3.17.1\src\mat\impls\aij\seq\aijmkl\aijmkl.c(177): warning C4003: not enough arguments for function-like macro invocation 'mkl_sparse_x_export_csr'

/spend 10m
Reported-by: Henrik Büsing <Henrik.Buesing@fgh-ma.de>