Revert "Remove dead code."
This reverts commit 91d67c071cd2d7e0716d4d3e7b881703a30409dc.

Reverting as this change caused link errors
/sandbox/petsc/petsc.master-3/arch-c-exodus-dbg-builder/lib/libpetsc.so: undefined reference to `KSPLSQRGetArnorm'