Fix compile warning in CUPM
petsc/src/vec/is/sf/impls/basic/cupm/cuda/../sfcupm_impl.hpp: In instantiation of 'static PetscErrorCode Petsc::sf::cupm::impl::SfInterface<T>::LinkSyncDevice(PetscSFLink) [with Petsc::device::cupm::DeviceType T = Petsc::device::cupm::DeviceType::CUDA; PetscSFLink = _n_PetscSFLink*]':
petsc/src/vec/is/sf/impls/basic/cupm/cuda/sfcupm.cu:18:17:   required from here
petsc/src/vec/is/sf/impls/basic/cupm/cuda/../sfcupm_impl.hpp:568:48: error: unused parameter 'link' [-Werror=unused-parameter]
  568 | inline PetscErrorCode SfInterface<T>::LinkSyncDevice(PetscSFLink link) noexcept
      |                                  ~~~~~~~~~~~~~~^~~~
cc1plus: all warnings being treated as errors
gmake[3]: *** [gmakefile:209: arch-gnu-c-cuda-int64/obj/src/vec/is/sf/impls/basic/cupm/cuda/sfcupm.o] Error 1