mpiuni: c8d2b952 was incomplete wrt change to using MPIUNI_FORTRAN_BINDING
fixes the following error with --with-mpi=0 --with-mpiuni-fortran-binding=0

/home/balay/petsc/arch-uni/lib/libpetsc.so: undefined reference to `mpi_init_'

Reported-by: Barry Smith <bsmith@mcs.anl.gov>