PetscCall: avoid in fortran source files - fixes line truncation errors when FFLAGS is set [and configure is unable to set -ffree-line-length-none]
CI: test empty FFLAGS to avoid this breakage


          FC arch-linux-c-debug/obj/sys/f90-mod/petscsysmod.o
/home/balay/petsc/src/sys/f90-mod/petscsysmod.F90:369:132:

  369 |              PetscCall(PetscInitializeF(trim(filename),PETSC_NULL_CHARACTER,PETSC_TRUE,ierr))
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]