demo/{perftest,poisson3d}: fixup linking failure when gcc flag wl,asneeded is used, e.g. in Ubuntu
mpicc -Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC    -o poisson3d.exe -L/usr/lib/petscdir/petsc3.10/x86_64-linux-gnu-real/lib -L/usr/lib/petscdir/petsc3.10/x86_64-linux-gnu-real/lib -L/usr/lib/x86_64-linux-gnu/hdf5/openmpi -L/usr/lib/openmpi/lib -L/usr/lib/x86_64-linux-gnu/openmpi/lib -L/usr/lib/gcc/x86_64-linux-gnu/8 -L/usr/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu -lpetsc_real -ldmumps -lzmumps -lsmumps -lcmumps -lmumps_common -lpord -lscalapack-openmpi -lumfpack -lamd -lcholmod -lklu -lsuperlu -lsuperlu_dist -lHYPRE_core -lfftw3 -lfftw3_mpi -llapack -lblas -lhdf5 -lmpi -lptesmumps -lptscotch -lptscotcherr -lm -lstdc++ -ldl -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lgfortran -lm -lgfortran -lm -lgcc_s -lquadmath -lpthread -lstdc++ -ldl poisson3d.o del2lib.o
/usr/bin/ld: poisson3d.o: in function `Del2Mat_mult':
/tmp/autopkgtest.h9u5hG/build.A4I/src/test-demos/poisson3d/del2mat.h:32: undefined reference to `MatShellGetContext'
/usr/bin/ld: /tmp/autopkgtest.h9u5hG/build.A4I/src/test-demos/poisson3d/del2mat.h:34: undefined reference to `VecGetArrayRead'
/usr/bin/ld: /tmp/autopkgtest.h9u5hG/build.A4I/src/test-demos/poisson3d/del2mat.h:35: undefined reference to `VecGetArray'
/usr/bin/ld: /tmp/autopkgtest.h9u5hG/build.A4I/src/test-demos/poisson3d/del2mat.h:39: undefined reference to `VecRestoreArrayRead'
/usr/bin/ld: /tmp/autopkgtest.h9u5hG/build.A4I/src/test-demos/poisson3d/del2mat.h:40: undefined reference to `VecRestoreArray'
/usr/bin/ld: /tmp/autopkgtest.h9u5hG/build.A4I/src/test-demos/poisson3d/del2mat.h:32: undefined reference to `PetscError'
/usr/bin/ld: /tmp/autopkgtest.h9u5hG/build.A4I/src/test-demos/poisson3d/del2mat.h:34: undefined reference to `PetscError'
/usr/bin/ld: /tmp/autopkgtest.h9u5hG/build.A4I/src/test-demos/poisson3d/del2mat.h:35: undefined reference to `PetscError'
/usr/bin/ld: /tmp/autopkgtest.h9u5hG/build.A4I/src/test-demos/poisson3d/del2mat.h:39: undefined reference to `PetscError'
/usr/bin/ld: /tmp/autopkgtest.h9u5hG/build.A4I/src/test-demos/poisson3d/del2mat.h:40: undefined reference to `PetscError'
/usr/bin/ld: poisson3d.o: in function `Del2Mat_diag':