CI: gcovr: use --exclude '.*/petscsys.h'
Avoids govr errors with this code change (with arch-ci-linux-cuda-uni-pkgs):

upgrading gcovr from v5.2 to v8.3 gives useful messages

AssertionError: Got function PetscStrHash(char const*) in /scratch/balay/petsc.x/include/petscsys.h on multiple lines: 2777, 2778.
        You can run gcovr with --merge-mode-functions=MERGE_MODE.

However gcovr v8.3 is causing many other job failures. Hence sticking with v5.2 [via: --exclude '.*/petscsys.h']