petscversion.h: is used by fortran sources - and should be excluded from clang-format
Reported-by: Carlos Alonso Aznarán Laos <caznaranl@uni.pe>

          FC arch-linux-c-opt/obj/sys/fsrc/somefort.o
/tmp/makepkg/petsc-complex/src/petsc-3.18.0/include/petscversion.h:13:4:

   13 |   #define PETSC_VERSION_GIT        "v3.18.0"
      |    1
Error: Invalid character in name at (1)