Build error: vecimpl.h:124:98: error: expected  declaration specifiers or '...' before string constant
Some C11 [and 17?] compilers break with this usage.

Can re-enable for these compilers when a better configure check is added